version: 2.1

orbs:
    browser-tools: circleci/browser-tools@1.1.0
    heroku: circleci/heroku@1.2.6

jobs:
    build-job:
        docker:
            - image: cimg/node:15.0.1-browsers

        working_directory: ~/presente

        steps:
            - browser-tools/install-browser-tools
            - checkout

            - run:
                  command: |
                      google-chrome --version
                  name: Check install

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: npm install
            - run: npm run build-prod

            - save_cache:
                  paths:
                      - node_modules
                      - dist
                      - package.json
                  key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}

            # run tests!
            - run: npm run test-ci

    deploy-job:
        docker:
            # replace with your preferred image
            - image: cimg/base
        steps:
            - heroku/deploy-via-git:
                app-name: $HEROKU_APP_NAME 
                api-key: HEROKU_API_KEY 
                branch: $CIRCLE_BRANCH 
                force: true
workflows:
    version: 2

    -build:
        jobs:
            - build-job
            - deploy-job:
                requires:
                    - build-job
            
filters:
    branches:
        only: master
