version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.3

jobs:
      build-job:
        docker:
            - image: circleci/node:14.17.0
            - image: cimg/node:13.12-browser

        working_directory: ~/presente

        steps:
            - checkout
            - browser-tools/install-chrome
            - browser-tools/install-chromedriver

            - run:
                command: |
                    google-chrome --version
                    chromedriver --version
                name: Check install

            # Download and cache dependencies
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    # fallback to using the latest cache if no exact match is found
                    - v1-dependencies-

            - run: yarn install
            - run: yarn run build

            - save_cache:
                paths:
                    - node_modules
                    - dist
                    - package.json
                    - firebase.json
                    - .firebaserc
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }} 

            # run tests!
            - run: yarn run test:unit 

workflows:
  version: 2

  -deploy:
    jobs:
      - build-job
      # - deploy-job:
      #     requires:
      #       - build-job
filters:
  branches:
    only: master